apiVersion: v1
kind: Pod 
metadata:
  name: secret-pod
  # namespace: roboshop
spec:
  containers:
  - name: secret-pod
    image: nginx
    ports: 
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-pod
