apiVersion: v1
kind: Pod 
metadata:
  name: config-pod-1
  # namespace: roboshop
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports: 
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-pod
