apiVersion: v1
kind: Pod 
metadata:
  name: hello-pod 
  # namespace: roboshop
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports: 
    - containerPort: 80
    env: 
    - name: kube-practice   # we can give anything here 
      valueFrom:  
        configMapKeyRef:
          name: devops-config # where to take 
          key: name  # what is the key 
    - name: learner   
      valueFrom:
        configMapKeyRef:
          name: devops-config # where to take 
          key: learner  # what is the key 