apiVersion: v1
kind: Pod 
metadata: 
  name: nginx-pod
  labels:  # using labeles here 
    app: nginx
    demo: Service  
  # namespace: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    ports: 
    - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata: 
  name: nginx-Service
spec:
  selector: # this is used to attach the service to pod by using the labels we gave sam elabel as above the servie will attach to above pods 
    app: nginx
    demo: Service
  ports:
    - protocol: TCP
      port: 80 #service port 
      targetPort: 80 # container port 


